services:
  key-management-service:
    container_name: key-management-service
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/kms/data
    environment:
      - CRON_ENABLED=true

volumes:
  data: